version: '3.8'

services:
  backend:
    build: ./back-end # Path to the backend Dockerfile
    container_name: backend_container
    restart: always
    depends_on:
      - mongodb
    ports:
      - 5000:5000 # Adjust if your backend runs on a different port
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/swimmingpool?authSource=admin
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - 27017:27017
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/admin?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass123 # Optional for UI authentication

volumes:
  mongodb_data:
